
net.Receive("AdminMenu", function()
 local frame = vgui.Create( "DFrame" )
frame:SetSize(1170, 388)
frame:Center()
frame:SetVisible(true)
frame:MakePopup()
frame:SetTitle("TTT Admin Settings by john drek")
frame:ShowCloseButton(false)
frame.Paint = function(s, w, h)
draw.RoundedBox(5, 2, 2, w-4,h-4,Color(28, 28, 28))
end

// MENU

local closeButton = vgui.Create("DButton", frame)
closeButton:SetPos(1140, 6)
closeButton:SetText("X")
closeButton:SetSize(25, 25)
function closeButton.DoClick()
    frame:Close()
    frame:SetDeleteOnClose(true)
end

local debugText = vgui.Create("DLabel", frame)
debugText:SetPos(8, 25)
debugText:SetText("Debug Settings")
debugText:SetSize(92, 27)

local AdminText = vgui.Create("DLabel", frame)
AdminText:SetPos(250, 25)
AdminText:SetText("Server Settings")
AdminText:SetSize(92, 27)

// DEBUG SETTINGS
local WinDebug = vgui.Create( "DCheckBoxLabel", frame )
WinDebug:SetPos(10, 55)
WinDebug:SetText("Prevent winning (debug)")
WinDebug:SetConVar("ttt_debug_preventwin")

local AdminScoreboard = vgui.Create( "DCheckBoxLabel", frame )
AdminScoreboard:SetPos(10, 80)
AdminScoreboard:SetText("Admin marked on scoreboard")
AdminScoreboard:SetConVar("ttt_highlight_admins")

local PrintTraitor = vgui.Create("DButton", frame)
PrintTraitor:SetSize(139, 25)
PrintTraitor:SetPos(10, 105)
PrintTraitor:SetText("Print all traitors (console)")
PrintTraitor:SetConsoleCommand("ttt_print_traitors")

local PrintPlayers = vgui.Create("DButton", frame)
PrintPlayers:SetSize(139, 25)
PrintPlayers:SetPos(10, 130)
PrintPlayers:SetText("Print playercount (console)")
PrintPlayers:SetConsoleCommand("ttt_print_playercount")

local PrintLastKills = vgui.Create("DButton", frame)
PrintLastKills:SetSize(139, 25)
PrintLastKills:SetPos(10, 155)
PrintLastKills:SetText("Restart round")
PrintLastKills:SetConsoleCommand("ttt_roundrestart")

local Traitor = vgui.Create("DButton", frame)
Traitor:SetSize(139, 25)
Traitor:SetPos(10, 180)
Traitor:SetText("Force Traitor")
Traitor:SetConsoleCommand("ttt_force_traitor")

local Innocent = vgui.Create("DButton", frame)
Innocent:SetSize(139, 25)
Innocent:SetPos(10, 205)
Innocent:SetText("Force Innocent")
Innocent:SetConsoleCommand("ttt_force_terror")

local Detective = vgui.Create("DButton", frame)
Detective:SetSize(139, 25)
Detective:SetPos(10, 230)
Detective:SetText("Force Detective")
Detective:SetConsoleCommand("ttt_force_detective")

// SERVER SETTINGS

// ROUND STRUCTURE

local prepTime = vgui.Create("DNumberWang", frame)
local prepTimeText = vgui.Create("DLabel", frame)
prepTimeText:SetPos(300, 55)
prepTimeText:SetSize(175, 27)
prepTimeText:SetText("Preparing time (seconds)")
prepTime:SetPos(250, 59)
prepTime:SetSize(44, 20)
prepTime:SetMin(1)
prepTime:SetConVar("ttt_preptime_seconds")

local firstPrepTime = vgui.Create("DNumberWang", frame)
local firstPrepTimeText = vgui.Create("DLabel", frame)
firstPrepTimeText:SetPos(300, 90)
firstPrepTimeText:SetSize(235, 27)
firstPrepTimeText:SetText("Preparing time of first round (seconds)")
firstPrepTime:SetPos(250, 94)
firstPrepTime:SetSize(44, 20)
firstPrepTime:SetMin(1)
firstPrepTime:SetConVar("ttt_firstpreptime")

local postTime = vgui.Create("DNumberWang", frame)
local postTimeText = vgui.Create("DLabel", frame)
postTimeText:SetPos(300, 130)
postTimeText:SetSize(235, 27)
postTimeText:SetText("Post time after round (seconds)")
postTime:SetPos(250, 133)
postTime:SetSize(44, 20)
postTime:SetMin(1)
postTime:SetConVar("ttt_posttime_seconds")


// ROUND LENGTH

local enableHaste = vgui.Create("DCheckBoxLabel", frame)
enableHaste:SetPos(250, 170)
enableHaste:SetText("Enable Haste Mode")
enableHaste:SetConVar("ttt_haste")

local startingHaste = vgui.Create("DNumberWang", frame)
local startingHasteText = vgui.Create("DLabel", frame)
startingHasteText:SetPos(300, 195)
startingHasteText:SetSize(235, 27)
startingHasteText:SetText("Start Haste Mode (minutes, only Haste Mode on)")
startingHaste:SetPos(250, 199)
startingHaste:SetSize(44, 20)
startingHaste:SetMin(1)
startingHaste:SetConVar("ttt_haste_starting_minutes")

local bonusHaste = vgui.Create("DNumberWang", frame)
local bonusHasteText = vgui.Create("DLabel", frame)
bonusHasteText:SetPos(300, 235)
bonusHasteText:SetSize(235, 27)
bonusHasteText:SetText("Bonus Haste Time for killing (Haste Mode only)")
bonusHaste:SetPos(250, 239)
bonusHaste:SetSize(44, 20)
bonusHaste:SetConVar("ttt_haste_minutes_per_death")

local roundTime = vgui.Create("DNumberWang", frame)
local roundTimeText = vgui.Create("DLabel", frame)
roundTimeText:SetPos(300, 275)
roundTimeText:SetSize(235, 27)
roundTimeText:SetText("Round time (minutes)")
roundTime:SetPos(250, 278)
roundTime:SetSize(44, 20)
roundTime:SetConVar("ttt_roundtime_minutes")
roundTime:SetMin(1)

// MAP SWITCHING AND VOTING

local roundLimit = vgui.Create("DNumberWang", frame)
local roundLimitText = vgui.Create("DLabel", frame)
roundLimitText:SetPos(300, 313)
roundLimitText:SetSize(235, 27)
roundLimitText:SetText("Round limit")
roundLimit:SetPos(250, 317)
roundLimit:SetSize(44, 20)
roundLimit:SetConVar("ttt_round_limit")
roundLimit:SetMin(1)

local timeLimit = vgui.Create("DNumberWang", frame)
local timeLimitText = vgui.Create("DLabel", frame)
timeLimitText:SetPos(300, 350)
timeLimitText:SetSize(235, 27)
timeLimitText:SetText("Time until the map is switched (minutes)")
timeLimit:SetPos(250, 355)
timeLimit:SetSize(44, 20)
timeLimit:SetConVar("ttt_time_limit_minutes")
timeLimit:SetMin(1)

// TRAITOR AND DETECTIVE

local maxTraitor = vgui.Create("DNumberWang", frame)
local maxTraitorText = vgui.Create("DLabel", frame)
maxTraitorText:SetPos(630, 52)
maxTraitorText:SetSize(235, 27)
maxTraitorText:SetText("Max traitors")
maxTraitor:SetPos(580, 56)
maxTraitor:SetSize(44, 20)
maxTraitor:SetConVar("ttt_traitor_max")
maxTraitor:SetMin(1)

local maxDete = vgui.Create("DNumberWang", frame)
local maxDeteText = vgui.Create("DLabel", frame)
maxDeteText:SetPos(630, 90)
maxDeteText:SetSize(235, 27)
maxDeteText:SetText("Max detectives")
maxDete:SetPos(580, 94)
maxDete:SetSize(44, 20)
maxDete:SetConVar("ttt_detective_max")
maxDete:SetMin(1)

local minDete = vgui.Create("DNumberWang", frame)
local minDeteText = vgui.Create("DLabel", frame)
minDeteText:SetPos(630, 128)
minDeteText:SetSize(235, 27)
minDeteText:SetText("Min players before detectives enter play")
minDete:SetPos(580, 130)
minDete:SetSize(44, 20)
minDete:SetConVar("ttt_detective_min_players")
minDete:SetMin(6)

local voiceChatBattery = vgui.Create("DCheckBoxLabel", frame)
voiceChatBattery:SetPos(580, 166)
voiceChatBattery:SetText("Voice Chat Battery")
voiceChatBattery:SetConVar("ttt_voice_drain")

local minPlayers = vgui.Create("DNumberWang", frame)
local minPlayersText = vgui.Create("DLabel", frame)
minPlayersText:SetPos(630, 200)
minPlayersText:SetSize(235, 27)
minPlayersText:SetText("Minimum players to start round")
minPlayers:SetPos(580, 204)
minPlayers:SetSize(44, 20)
minPlayers:SetConVar("ttt_minimum_players")
minPlayers:SetMin(2)

local postRoundDM = vgui.Create("DCheckBoxLabel", frame)
postRoundDM:SetPos(580, 240)
postRoundDM:SetText("Post Round DM")
postRoundDM:SetConVar("ttt_postround_dm")

local noNade = vgui.Create("DCheckBoxLabel", frame)
noNade:SetPos(580, 280)
noNade:SetText("Throwing grenades during preparation time")
noNade:SetConVar("ttt_no_nade_throw_during_prep")

local ragdolPinning = vgui.Create("DCheckBoxLabel", frame)
ragdolPinning:SetPos(580, 318)
ragdolPinning:SetText("Ragdoll pinning")
ragdolPinning:SetConVar("ttt_ragdoll_pinning")

local ragdollPinningI = vgui.Create("DCheckBoxLabel", frame)
ragdollPinningI:SetPos(580, 355)
ragdollPinningI:SetText("Ragdoll pinning as Innocent (not recommended)")
ragdollPinningI:SetConVar("ttt_ragdoll_pinning_innocents")

local propPossesion = vgui.Create("DCheckBoxLabel", frame)
propPossesion:SetPos(880, 56)
propPossesion:SetText("Prop Possesion by Spectators")
propPossesion:SetConVar("ttt_spec_prop_control")

local idleTime = vgui.Create("DNumberWang", frame)
local idleTimeT = vgui.Create("DLabel", frame)
idleTime:SetPos(880, 90)
idleTime:SetSize(44, 20)
idleTimeT:SetPos(935, 90)
idleTimeT:SetSize(235, 27)
idleTimeT:SetText("Idle Time (seconds)")
idleTime:SetConVar("ttt_idle_limit")

local nameCheck = vgui.Create("DCheckBoxLabel", frame)
nameCheck:SetPos(880, 135)
nameCheck:SetText("Check for name changes during round")
nameCheck:SetConVar("ttt_namechange_kick")

local nameBanTime = vgui.Create("DNumberWang", frame)
local nameBanTimeT = vgui.Create("DLabel", frame)
nameBanTime:SetPos(880, 175)
nameBanTime:SetSize(44, 20)
nameBanTimeT:SetPos(935, 171)
nameBanTimeT:SetSize(235, 27)
nameBanTimeT:SetText("Time of ban player who changed name (minutes)")
nameBanTime:SetConVar("ttt_namechange_bantime")
nameBanTime:SetMin(10)

// KARMA 

local karmaFrame = vgui.Create("DFrame")
karmaFrame:SetVisible(false)
karmaFrame:MakePopup()
karmaFrame.Paint = function(s, w, h)
karmaFrame:ShowCloseButton(false)
draw.RoundedBox(5, 2, 2, w-4,h-4,Color(28, 28, 28))
end

local karmaButton = vgui.Create("DButton", frame)
karmaButton:SetPos(10, 280)
karmaButton:SetSize(139, 25)
karmaButton:SetText("Karma Settings")

function karmaButton.DoClick ()
    karmaFrame:SetVisible(true)
    karmaFrame:Center()
    karmaFrame:SetSize(229, 386)
    karmaFrame:SetTitle("Karma Settings")
end

closeKarma = vgui.Create("DButton", karmaFrame)
closeKarma:SetSize(25, 25)
closeKarma:SetPos(205, 1)
closeKarma:SetText("X")
function closeKarma.DoClick ()
    karmaFrame:Close()
    karmaFrame:SetDeleteOnClose(true)
end

enableKarma = vgui.Create("DCheckBoxLabel", karmaFrame)
enableKarma:SetPos(10, 35)
enableKarma:SetText("Enable Karma")
enableKarma:SetConVar("ttt_karma")

strictKarma = vgui.Create("DCheckBoxLabel", karmaFrame)
strictKarma:SetPos(10, 65)
strictKarma:SetText("Strict Karma (more dmg penatly)")
strictKarma:SetConVar("ttt_karma_strict")

startKarma = vgui.Create("DNumberWang", karmaFrame)
startKarmaText = vgui.Create("DLabel", karmaFrame)
startKarma:SetPos(10, 95)
startKarmaText:SetPos(65, 95)
startKarmaText:SetText("Start Karma")
startKarma:SetSize(44, 20)
startKarma:SetConVar("ttt_karma_starting")
startKarma:SetMin(1000)

local autokick = vgui.Create("DCheckBoxLabel", karmaFrame)
autokick:SetPos(10, 125)
autokick:SetText("Autokick for low karma")
autokick:SetConVar("ttt_karma_low_autokick")

local lowAmount = vgui.Create("DNumberWang", karmaFrame)
local lowAmountText = vgui.Create("DLabel", karmaFrame)
lowAmount:SetPos(10, 155)
lowAmountText:SetPos(65, 150)
lowAmount:SetSize(44, 20)
lowAmount:SetConVar("ttt_karma_low_amount")
lowAmountText:SetSize(235, 27)
lowAmountText:SetText("Karma threshold")
lowAmount:SetMin(450)

local banKarma = vgui.Create("DCheckBoxLabel", karmaFrame)
banKarma:SetPos(10, 185)
banKarma:SetText("Ban if autokicked for low karma")
banKarma:SetConVar("ttt_karma_low_ban")

local timeBan = vgui.Create("DNumberWang", karmaFrame)
local timeBanText = vgui.Create("DLabel", karmaFrame)
timeBan:SetPos(10, 215)
timeBanText:SetPos(65, 210)
timeBan:SetSize(44, 20)
timeBan:SetConVar("ttt_karma_low_ban_minutes")
timeBanText:SetSize(235, 27)
timeBanText:SetText("Length of ban for low karma")
timeBan:SetMin(10)

local debugKarma = vgui.Create("DCheckBoxLabel", karmaFrame)
debugKarma:SetPos(10, 245)
debugKarma:SetText("Always print karma changes")
debugKarma:SetConVar("ttt_karma_debugspam")

// TRAITOR AND DETECTIVE CREDITS

local creditsSettings = vgui.Create("DFrame")
creditsSettings:SetVisible(false)
creditsSettings:MakePopup()
creditsSettings:ShowCloseButton(false)
creditsSettings.Paint = function(s, w, h)
draw.RoundedBox(5, 2, 2, w-4,h-4,Color(28, 28, 28))
end

local creditsButton = vgui.Create("DButton", frame)
creditsButton:SetPos(10, 315)
creditsButton:SetSize(139, 25)
creditsButton:SetText("Credits Settings")

local creditsClose = vgui.Create("DButton", creditsSettings)
creditsClose:SetSize(25, 25)
creditsClose:SetPos(325, 1)
creditsClose:SetText("X")

function creditsClose.DoClick ()
    creditsSettings:Close()
    creditsSettings:SetDeleteOnClose(true)
end

function creditsButton.DoClick ()
    creditsSettings:SetVisible(true)
    creditsSettings:Center()
    creditsSettings:SetSize(354, 210)
    creditsSettings:SetTitle("Credits Settings")
end


local creditsStart = vgui.Create("DNumberWang", creditsSettings)
local creditsStartText = vgui.Create("DLabel", creditsSettings)
creditsStart:SetPos(10, 35)
creditsStart:SetSize(44, 20)
creditsStartText:SetPos(65, 31)
creditsStartText:SetSize(235, 27)
creditsStartText:SetText("Set starting credits for traitors")
creditsStart:SetConVar("ttt_credits_starting")
creditsStart:SetMin(1)

local creditsAward = vgui.Create("DNumberWang", creditsSettings)
local creditsAwardText = vgui.Create("DLabel", creditsSettings)
creditsAward:SetPos(10, 65)
creditsAward:SetSize(44, 20)
creditsAwardText:SetPos(65, 61)
creditsAwardText:SetSize(235, 27)
creditsAwardText:SetText("Number of credits awarded")
creditsAward:SetConVar("ttt_credits_award_size")
creditsAward:SetMin(1)

local creditsAwardDete = vgui.Create("DNumberWang", creditsSettings)
local creditsAwardDeteT = vgui.Create("DLabel", creditsSettings)
creditsAwardDete:SetPos(10, 95)
creditsAwardDete:SetSize(44, 20)
creditsAwardDeteT:SetPos(65, 91)
creditsAwardDeteT:SetSize(235, 27)
creditsAwardDeteT:SetText("Number of credits awarded for killing detective")
creditsAwardDete:SetConVar("ttt_credits_detectivekill")
creditsAwardDete:SetMin(1)

local creditsStartD = vgui.Create("DNumberWang", creditsSettings)
local creditsStartDT = vgui.Create("DLabel", creditsSettings)
creditsStartD:SetPos(10, 125)
creditsStartD:SetSize(44, 20)
creditsStartDT:SetPos(65, 121)
creditsStartDT:SetSize(235, 27)
creditsStartDT:SetText("Set starting credits for detectives")
creditsStartD:SetConVar("ttt_det_credits_starting")
creditsStartD:SetMin(1)

local creditsKillT = vgui.Create("DNumberWang", creditsSettings)
local creditsKillTText = vgui.Create("DLabel", creditsSettings)
creditsKillT:SetPos(10, 155)
creditsKillT:SetSize(44, 20)
creditsKillTText:SetPos(65, 151)
creditsKillTText:SetSize(235, 27)
creditsKillTText:SetText("Number of credits awarded for killing traitor")
creditsKillT:SetConVar("ttt_det_credits_traitorkill")

local creditsDead = vgui.Create("DNumberWang", creditsSettings)
local creditsDeadT = vgui.Create("DLabel", creditsSettings)
creditsDead:SetPos(10, 185)
creditsDead:SetSize(44, 20)
creditsDeadT:SetPos(65, 181)
creditsDeadT:SetSize(235, 27)
creditsDeadT:SetText("Number of credits awarded for death of traitor")
creditsDead:SetConVar("ttt_det_credits_traitordead")
creditsDead:SetMin(1)
end)


